apiVersion: v2
name: whisper-transcription
description: A Helm chart for deploying the Whisper Transcription app

type: application

version: 0.3.7
appVersion: "v0.3.7"

maintainers:
  - name: Mateo Langston Smith
    email: mlangstonsmith@smu.edu